### ISSUE TITLE
arch=turing not recoginized by nvidia-container-cli

### ISSUE THREAD

**Issue by xunlwu** [NVIDIA/nvidia-container-runtime#109]
Hello,

I would like to restrict the Kubernetes container starts on GPU's with architecture pascal, volta, turing, or ampere. However, when including "arch=turing" in the value of NVIDIA_REQUIRE_ARCH in a pod resource yaml file, nvidia-container-cli complains "requirement error: invalid expression\\\\n\\\"\"": unknown".

        env:
...
        - name: NVIDIA_REQUIRE_ARCH
        #  value: arch=pascal arch=volta arch=ampere
          value: arch=pascal arch=volta arch=turing arch=ampere
...  

Below is the excerption of kubectl describe pod <my_pod>.

Containers:
...
    Last State:     Terminated
      Reason:       ContainerCannotRun
      Message:      OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:385: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: requirement error: invalid expression\\\\n\\\"\"": unknown
      Exit Code:    128

If I drop arch=turing from the list, the pod creation no longer produces nvidia-container-cli error message. I wonder whether "turing" keyword/enum is not included in nvidia-container-cli. 

Would you please tell me the correct way to achieve such requirement? 
Thank you very much.

**Comment by xunlwu** [comment]
Can anyone provide some suggestions please?

**Comment by supertetelman** [comment]
Hello,

I've typically seen people restrict where certain GPU workloads run by using NodeLabels and NodeSelectors along with the GPU Feature Discovery tool (https://github.com/NVIDIA/gpu-feature-discovery).

Running that tool is a quick helm install and it will automatically label all the nodes in your cluster with the type of GPU that is present. After that you can update your Pod YAML with the NodesSelectors associated with your Turing cards.

If that doesn't work for you, it might be helpful to see the output of `kubectl describe` for your node and a bit more of the Pod YAML.

**Comment by xunlwu** [comment]
Thank you, supertetelman.
I understand selecting node through node label. My cluster nodes already have certain gpu features
                    `gpu.nvidia.com/brand=tesla`
                    `gpu.nvidia.com/family=volta`
My goal is to restrict pod from launching on nodes with GPU architecture other than pascal, volta, turing, and ampere. I don't mind having a cluster started on a set of nodes with mixed GPU architectures as long as they are part of the forementioned four code names.

**Comment by supertetelman** [comment]
You can force your Pod to run on a Node with **any** of a list of GPU types with something like the below:
```
apiVersion: v1
kind: Pod
metadata:
  name: example
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "gpu.nvidia.com/family"
            operator: In
            values:
            - pascal
            - volta
            - turing 
            - ampere   
```

And you can swap out the Operator to restrict a Pod to not run on a specific GPU type:
```
apiVersion: v1
kind: Pod
metadata:
  name: example
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "gpu.nvidia.com/family"
            operator: NotIn
            values:
            - kepler
            - ""
```
