### ISSUE TITLE
Podman `nvidia-smi` not found when using `--gpus`

### ISSUE THREAD

**Issue by raldone01** [NVIDIA/nvidia-container-runtime#190]
Works:
* `sudo docker run --rm --device nvidia.com/gpu=all ubuntu nv
idia-smi -L`
* `sudo podman run --rm --device nvidia.com/gpu=all ubuntu nv
idia-smi -L`
Does not work:
* `sudo docker run --rm --gpus all ubuntu nv
idia-smi -L`
* `sudo podman run --rm --gpus all ubuntu nv
idia-smi -L`

The `--gpus all` commands fail with the following output:
```
Error: crun: executable file `nvidia-smi` not found in $PATH: No such file or directory: OCI runtime attempted to invoke a command that was not found
```

I have installed `nvidia-container-toolkit` and ran `sudo nvidia-ctk cdi generate --output=/etc/cdi/nvidia.yaml`.

I have no idea what is wrong.

**Comment by elezar** [comment]
One note: `sudo podman run --rm --gpus all ubuntu nvidia-smi -L` would not be expected to work. The `--gpus` flag in podman is a no-op argument that is only provided for compatibility with the Docker CLI.

Which version(s) of the NVIDIA Container Toolkit packages are installed on the system? The `--gpus` flag in Docker requires that the `nvidia-container-runtime-hook` be installed when the docker daemon is started. Does restarting the daemon help in this case?

**Comment by raldone01** [comment]
Thanks for your reply.

```
❯ nvidia-container-runtime-hook --version
NVIDIA Container Runtime Hook version 1.13.5
❯ nvidia-container-toolkit --version
NVIDIA Container Runtime Hook version 1.13.5
❯ ls /usr/share/containers/oci/hooks.d/
00-oci-nvidia-hook.json
```

If `--gpus` is provided for compatibility and is not properly implemented it should at least issue a warning that it has been ignored.
I could not figure out why it did nothing.

I do not have a docker daemon running as I use podman. (daemon.json does not exist)
I have a podman daemon running that emulates the docker api.

Does `sudo podman run --rm --device nvidia.com/gpu=all ubuntu nvidia-smi -L` load the hooks?
How does the container runtime know when to load which hook?

I do not know how docker-compose works internally.
If it calls the docker cli with the `--gpus` option it is clear why it doesn't work as podman just ignores it.

So far I have not had compatibility issues with `docker-compose`.
Should I also take this issue to podman, docker-compose or somewhere else?
Do I have other options than switching back to docker again?

**Comment by raldone01** [comment]
> We do not maintain the podman implementation of `--gpus`, you will need to open an issue with `podman`directly.

Will do.

Ok so `podman` is actually front running? Interesting.

The following syntax does not work with my current setup.
```yml
deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # device_ids: ["GPU-XXX"]
              count: 1
              capabilities: [gpu, utility, compute]
```
I was under the impression that this is the new and recommended approach even supporting device ids.
I am pretty sure that this is an issue with the `docker->podman` emulation.

Can you link me to the proper syntax of the `--device` option?

I only found information about the mapping syntax: `--device=/dev/sdc:/dev/xvdc:rwm`

If I want to pass through two specific gpus can I just write `--device nvidia.com/gpu=GPU-XXX-XXX-1 --device nvidia.com/gpu=GPU-XXX-XXX-2`?

Do you know how/if `cdi` support is planned in `docker-compose`?
Can you link me to resources about `cdi`?

Is there a way to get `docker-compose` to work?

**Comment by elezar** [comment]
CDI Support in Docker will be an experimental feature in the Docker 25 release that has not yet gone out. With this in place, CDI should already be supported in Docker Compose with following `services` section:
```
services:
  test:
    image: application-image
    command: do-the-thing
    deploy:
      resources:
        reservations:
          devices:
            # NVIDIA Devices
            - driver: cdi
              deviceIDs:
                - nvidia.com/gpu=0
                - nvidia.com/gds=all
                - nvidia.com/mofed=all
            # Intel Devices
            - driver: cdi
              deviceIDs:
                - intel.com/vf=0
                - intel.com/fpga=fist
```
Note the `cdi` driver and the device IDs specifying fully-qualified CDI device names.

This means that if you:
1. Have the NVIDIA Container Toolkit (e.g. v1.13.5) installed
2. Have generated the CDI specification for NVIDIA GPUs by running `sudo nvidia-ctk cdi generate --output=/etc/cdi/nvidia.yaml --device-name-strategy=uuid`
3. Have a v25 Docker daemon configured in experimental mode

Then specifying the devices through `--device=nvidia.com/gpu={{GPU_UUID}}` or in the Docker compose specification.

We are still in the process of improving our documentation around CDI and its use in the various runtimes that support it.
